# Course Title: Data Analytics & Statistics in Python
## Metropolia University of Applied Sciences
## Week 2: Matrices, DataFrames, and Time-Series Data
### Date: 12.3.2025

<table "<table style="width: 100%;">
  <tr>
    <td style="text-align: left; vertical-align: middle;">
      <ul style="list-style: none; padding-left: 0;">
        <li><strong>Instructor</strong>: Hamed Ahmadinia, Ph.D</li>
        <li><strong>Email</strong>: hamed.ahmadinia@metropolia.fi
        <li><strong>Web</strong>: www.ahmadinia.fi</li>          </li>
      </ul>
    </td>
  </tr>
</table>

## **1. Loading the Dataset**

### **Loading the Bike Sales Dataset**  
We will load the **Bike Sales Dataset** from the provided GitHub URL. This dataset contains demographic and sales data related to bike purchases.  
Let’s load the data and display the first few rows to understand its structure.

In [ ]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning) # suppress mathematically undefined errors

# Import necessary libraries
import pandas as pd  # pandas is used for handling tabular datasets (dataframes) and performing operations such as reading CSV files
import numpy as np  # numpy is used for numerical computations such as working with arrays and applying mathematical operations

# Load dataset from GitHub URL
file_path = "https://raw.githubusercontent.com/Hamed-Ahmadinia/DASP-2025/main/Bike%20Sales.csv"  # URL link to the dataset stored on GitHub

# Read the dataset into a pandas dataframe
df = pd.read_csv(file_path)  # Load the dataset as a pandas DataFrame

# Display the first few rows of the dataframe to confirm the data has been loaded correctly
print("Dataset Preview:")  # Print a label for context
print(df.head(5))  # Display the first 5 rows of the dataset

Dataset Preview:
         Date  Day     Month  Year  Customer_Age       Age_Group  \
0  2013-11-26   26  November  2013            19     Youth (<25)   
1  2015-11-26   26  November  2015            19     Youth (<25)   
2  2014-03-23   23     March  2014            49  Adults (35-64)   
3  2016-03-23   23     March  2016            49  Adults (35-64)   
4  2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack 

# 2. Arrays and Matrices in Python

### **2.1 NumPy Arrays**

**What is a NumPy Array?**  
A **NumPy array** is a **powerful** data structure used in Python for **numerical computations**. It is a collection of **homogeneous elements** (usually numbers) arranged in a **contiguous block of memory**. NumPy arrays are similar to Python lists but offer **faster computations** and **efficient storage**.

---

### **Key Characteristics of NumPy Arrays:**

| **Feature**         | **Description**                                                                 |
|---------------------|----------------------------------------------------------------------------------|
| **Fixed Size**       | Once created, the size of a NumPy array cannot be changed.                       |
| **Homogeneous Type** | All elements in a NumPy array must have the same data type (e.g., integers).     |
| **Efficient Storage**| Arrays use a contiguous block of memory, making access and operations faster.    |
| **Vectorized Ops**   | Element-wise operations (e.g., addition, multiplication) can be applied directly.|

---

### **Why Use NumPy Arrays?**  

1. **Performance**: NumPy arrays are implemented in C and are much faster than Python lists.
2. **Convenient Indexing**: Supports **multi-dimensional** indexing and slicing.
3. **Linear Algebra Operations**: NumPy has built-in support for **matrix operations** like **dot products** and **matrix multiplication**.

---

### **Creating NumPy Arrays**

NumPy arrays can be created in various ways:
1. **From Lists**: You can convert a Python list to a NumPy array using `np.array()`.
2. **Using Functions**: You can create arrays using functions like `arange()`, `linspace()`, `zeros()`, `ones()`, and `random()`.

---



In [ ]:
# Extract the 'Revenue' column as a NumPy array
revenue_array = df['Revenue'].to_numpy()

# Show the first 5 values to understand the data
print(revenue_array[:5])

[ 950  950 2401 2088  418]


In [ ]:
# --- Key Characteristics of NumPy Arrays ---
print("Characteristics of the Revenue Array:")

# Fixed size of the array
array_size = revenue_array.size
print(f"Total number of elements in the array: {array_size}")

# Homogeneous data type
array_dtype = revenue_array.dtype
print(f"Data type of elements: {array_dtype}")

Characteristics of the Revenue Array:
Total number of elements in the array: 113036
Data type of elements: int64


In [ ]:
# Element-wise operation example (doubling values)
revenue_array_doubled = revenue_array * 2
print("Doubled Revenue Values (First 10):")
print(revenue_array_doubled[:10])

Doubled Revenue Values (First 10):
[1900 1900 4802 4176  836 1044  758  380 4172 3982]


In [ ]:
# Indexing and slicing example
subset_revenue = revenue_array[:5]
print("Subset of Revenue (First 5 Values):")
print(subset_revenue)

Subset of Revenue (First 5 Values):
[ 950  950 2401 2088  418]


In [ ]:
# Create an array using np.arange (values from 1 to 10)
arange_array = np.arange(1, 11)
print("Array created with np.arange (1 to 10):")
print(arange_array)

Array created with np.arange (1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Create an array filled with zeros
zeros_array = np.zeros(5)
print("Array of Zeros (Length 5):")
print(zeros_array)

Array of Zeros (Length 5):
[0. 0. 0. 0. 0.]


In [ ]:
# Create a 3x3 random array
random_array = np.random.rand(3, 3)
print("Random 3x3 Array (Values between 0 and 1):")
print(random_array)

Random 3x3 Array (Values between 0 and 1):
[[0.74767781 0.4789142  0.67393981]
 [0.67348951 0.8030313  0.58458662]
 [0.75366764 0.56937257 0.55697789]]


### **2.2 Reshaping Arrays**

**Reshaping an Array:**  
In NumPy, you can **change the shape of an array** using the `reshape()` method. Reshaping is useful when you need to convert between **1D, 2D, or 3D arrays** without altering the actual data.

---

### **Key Points about Reshaping:**
1. The **total number of elements** must remain the same.
   - Example: A 1D array with 6 elements can be reshaped to **2x3** (2 rows, 3 columns) or **3x2** (3 rows, 2 columns).
2. You can use `-1` to let NumPy **automatically calculate** one of the dimensions.
3. Reshaping is commonly used in **data preprocessing**, **linear algebra**, and **machine learning tasks**.

---

### **Why Reshaping is Important:**
- **Data Preprocessing:** Often, data needs to be reshaped into a matrix format before being fed into machine learning models.
- **Matrix Operations:** Reshaping makes it easy to apply matrix multiplication and transformations.
- **Flattening Arrays:** Reshaping to a 1D array simplifies vectorized operations.

---

### **Illustration of NumPy Arrays**

Below is a visual representation of a NumPy array and its structure:

<div style="text-align: center;">
  <img src="https://www.pythontutorial.net/wp-content/uploads/2022/08/what-is-numpy-1024x572.png" alt="NumPy Arrays Example" width="400">
</div>

- **1D Array:** A linear sequence of elements (shape `(n,)`, e.g., `[7, 2, 9, 10]`).
- **2D Array:** A matrix with rows and columns (shape `(rows, columns)`, e.g., `[[5.2, 3.0], [9.1, 0.1]]`).
- **3D Array:** A cube or collection of 2D matrices (shape `(depth, rows, columns)`).
---


In [ ]:
# Reshape to a 2D array ---
print("Reshape to 2D Array (4 rows, 3 columns):")
reshaped_2d = subset_array.reshape(4, 3)
print(reshaped_2d)
print(f"New Shape: {reshaped_2d.shape}")

Reshape to 2D Array (4 rows, 3 columns):
[[ 950  950 2401]
 [2088  418  522]
 [ 379  190 2086]
 [1991  758  758]]
New Shape: (4, 3)


In [ ]:
# Reshape to a 3D array ---
print("Reshape to 3D Array (2 blocks, 2 rows, 3 columns):")
reshaped_3d = subset_array.reshape(2, 2, 3)
print(reshaped_3d)
print(f"New Shape: {reshaped_3d.shape}")

Reshape to 3D Array (2 blocks, 2 rows, 3 columns):
[[[ 950  950 2401]
  [2088  418  522]]

 [[ 379  190 2086]
  [1991  758  758]]]
New Shape: (2, 2, 3)


In [ ]:
# Adding a New Axis ---
print("Add a New Axis (convert to 2D shape with one column):")
new_axis_array = subset_array[:, np.newaxis]
print(new_axis_array)
print(f"New Shape: {new_axis_array.shape}")

Add a New Axis (convert to 2D shape with one column):
[[ 950]
 [ 950]
 [2401]
 [2088]
 [ 418]
 [ 522]
 [ 379]
 [ 190]
 [2086]
 [1991]
 [ 758]
 [ 758]]
New Shape: (12, 1)


# 3. Working with NumPy Arrays

### **3.1 Special Values in Arrays**

NumPy provides **special values** like `NaN` (Not a Number) and `inf` (infinity) to handle missing or infinite data.

---

### **Why Use Special Values?**
- Real-world datasets often contain **missing or corrupted data points** (e.g., incomplete survey responses).
- Special values help identify, process, and **handle problematic data points** to avoid calculation errors or misleading results.

---

### **Types of Special Values:**

| **Special Value** | **Meaning**                          | **Usage Example**          | **Notes**                                |
|-------------------|--------------------------------------|---------------------------|-----------------------------------------|
| **`NaN`**         | Not a Number (represents missing data)| `np.nan`                   | `np.isnan()` returns `True` for `NaN` values. |
| **`inf`**         | Positive infinity                     | `np.inf`                   | Represents values that exceed numerical limits (e.g., dividing by 0). |
| **`-inf`**        | Negative infinity                     | `-np.inf`                  | Used when values trend infinitelh_nan)}")  # True for NaN, False otherwise


In [ ]:
# Create an array containing special values (mean Revenue, NaN, positive infinity, negative infinity)
mean_revenue = df['Revenue'].mean()  # Calculate mean revenue for demonstration
special_values_array = np.array([mean_revenue, np.nan, np.inf, -np.inf])

print("Special Values Array (mean, NaN, +inf, -inf):")
print(special_values_array)

Special Values Array (mean, NaN, +inf, -inf):
[754.37035989          nan          inf         -inf]


In [ ]:
# Boolean mask to check for NaN values
print(np.isnan(special_values_array))

[False  True False False]


In [ ]:
# Boolean mask to check for infinity values (both +inf and -inf)
print(np.isinf(special_values_array))

[False False  True  True]


# 4. Pandas DataFrames

### **4.1 Introduction to Pandas DataFrames**

### **What is a Pandas DataFrame?**
- A **Pandas DataFrame** is a **two-dimensional, labeled data structure** that stores data in **rows and columns**.
- It’s similar to a **table** in databases or a **spreadsheet** in Excel.
- DataFrames are powerful because they allow:
  - **Efficient data manipulation** (e.g., filtering, sorting, merging).
  - Easy handling of **missing data**.
  - Support for **various data types** (e.g., integers, strings, floats).

---

### **Why Use Pandas?**
- Pandas integrates well with other **data science libraries** like:
  - **Matplotlib** (for data visualization).
  - **Scikit-learn** (for machine learning tasks).
- **Key features of Pandas DataFrames:**
  - Easy **data cleaning** and **preprocessing**.
  - Built-in functions for **grouping**, **merging**, and **aggregating**.
  - **Seamless integration** with file formats (e.g., CSV, Excel, SQL databases).

---

### **Illustration of Pandas DataFrames**

<div style="text-align: center;">
  <img src="https://lh6.googleusercontent.com/proxy/qK5kiy5vtoJ3cvU49t1MGs0o2SX-R07F_JyVQyuYLXITIjWsiqY237gNHNY1B0sY8iIzIh5g1BcxRaq4WmoDbxuD6RCGXgzSUZs" alt="Pandas DataFrame Example" width="400">
</div>

---

### **Explanation of Pandas DataFrames**

1. **Label Index (Rows)**:  
   - Shown in **blue** in the image.
   - Acts as unique identifiers (e.g., country codes such as `IT`, `ES`, `GR`, etc.).
   - Helps reference data by label instead of row number.

2. **Column Names**:
   - Shown as **header labels** (`Country`, `Popu`, `Percent`).
   - Represent the names of the features/variables in the dataset.

3. **Data**:
   - The main table content.
   - Contains values such as country names (`Italy`, `Spain`), population values (`61`, `46`), and percentage values (`0.83`, `0.63`).
   - Columns can hold **different types of data** (e.g., `Country` stores strings, `Popu` stores integers, `Percent` stores floats).

4. **Indexing and Labeling**:
   - The **label index** allows accessing rows by a label (e.g., `IT` for `Italy`).
   - This makes operations like filtering and selection more intuitive.

--- 


In [ ]:
# Preview the first row of the DataFrame
print(df.head(1))

         Date  Day     Month  Year  Customer_Age    Age_Group Customer_Gender  \
0  2013-11-26   26  November  2013            19  Youth (<25)               M   

  Country             State Product_Category Sub_Category  \
0  Canada  British Columbia      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike               8         45         120     590   360   

   Revenue  
0      950  


In [ ]:
# General information about the DataFrame (column names, non-null counts, data types)
df.info()  # No need for `print()` since `info()` displays automatically

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64 
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64 
 4   Customer_Age      113036 non-null  int64 
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64 
 13  Unit_Cost         113036 non-null  int64 
 14  Unit_Price        113036 non-null  int64 
 15  Profit            113036 non-null  int64 
 16  Cost              113036 non-null  int

In [ ]:
# Summary statistics for numeric columns (e.g., mean, min, max)
print(df.describe())

                 Day           Year   Customer_Age  Order_Quantity  \
count  113036.000000  113036.000000  113036.000000   113036.000000   
mean       15.665753    2014.401739      35.919212       11.901660   
std         8.781567       1.272510      11.021936        9.561857   
min         1.000000    2011.000000      17.000000        1.000000   
25%         8.000000    2013.000000      28.000000        2.000000   
50%        16.000000    2014.000000      35.000000       10.000000   
75%        23.000000    2016.000000      43.000000       20.000000   
max        31.000000    2016.000000      87.000000       32.000000   

           Unit_Cost     Unit_Price         Profit           Cost  \
count  113036.000000  113036.000000  113036.000000  113036.000000   
mean      267.296366     452.938427     285.051665     469.318695   
std       549.835483     922.071219     453.887443     884.866118   
min         1.000000       2.000000     -30.000000       1.000000   
25%         2.000000    

In [ ]:
# Check the shape of the DataFrame (number of rows and columns)
print(f"Number of Rows: {df.shape[0]}, Number of Columns: {df.shape[1]}")

Number of Rows: 113036, Number of Columns: 18


In [ ]:
# Display the column names
print(df.columns.tolist())

['Date', 'Day', 'Month', 'Year', 'Customer_Age', 'Age_Group', 'Customer_Gender', 'Country', 'State', 'Product_Category', 'Sub_Category', 'Product', 'Order_Quantity', 'Unit_Cost', 'Unit_Price', 'Profit', 'Cost', 'Revenue']


In [ ]:
# Access a single column ('Revenue') as a Series
print(df['Revenue'].head(5))

0     950
1     950
2    2401
3    2088
4     418
Name: Revenue, dtype: int64


In [ ]:
# Access multiple columns ('Country', 'State', 'Revenue') as a new DataFrame
print(df[['Country', 'State', 'Revenue']].head())

     Country             State  Revenue
0     Canada  British Columbia      950
1     Canada  British Columbia      950
2  Australia   New South Wales     2401
3  Australia   New South Wales     2088
4  Australia   New South Wales      418


In [ ]:
# Select rows using iloc (numerical index-based)
print(df.iloc[0:3])

         Date  Day     Month  Year  Customer_Age       Age_Group  \
0  2013-11-26   26  November  2013            19     Youth (<25)   
1  2015-11-26   26  November  2015            19     Youth (<25)   
2  2014-03-23   23     March  2014            49  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike               8         45         120     590   360   
1  Hitch Rack - 4-Bike               8         45         120     590   360   
2  Hitch Rack - 4-Bike              23         45         120    1366  1035   

   Revenue  
0      950  
1      950  
2     2401  


# 5. Editing and Filtering Data

### **5.1 Handling Missing Data**

### **Why Handle Missing Data?**  
Real-world datasets often contain missing or incomplete information due to:  
- Human errors (e.g., unanswered survey questions).  
- System issues (e.g., sensor malfunctions).  
- Data collection issues (e.g., lost records).  

Missing data can cause issues such as:  
- Errors during calculations.  
- Skewed results due to incomplete analysis.  

---

### **Common Pandas Methods for Handling Missing Data**

| **Method**   | **Description**                                                                            | **Example**                       |
|--------------|---------------------------------------------------------------------------------------------|------------------------------------|
| `dropna()`   | Removes rows/columns with missing values.                                                    | `df.dropna()`                     |
| `fillna()`   | Replaces missing values with a specified value (e.g., `0`, mean, median).                    | `df.fillna(0)`                     |
| `isna()`     | Returns a DataFrame of `True` for missing values and `False` otherwise.                      | `df.isna()`                        |
| `notna()`    | Returns a DataFrame of `True` for non-missing values and `False` otherwise.                  | `df.notna()`                       |

---

### **Illustration of Missing Data**

<div style="text-align: center;">
  <img src="https://www.solver.com/sites/default/files/ExamplesxlsxScreenshot1_2.jpg" alt="Missing Data Example" width="300">
</div>  

The image above shows missing data represented as blank cells (`NaN` in Pandas).

---


In [ ]:
# Check for missing values in each column
missing_values = df.isna().sum()  # Number of missing values per column
print(missing_values)

Date                0
Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             0
State               0
Product_Category    0
Sub_Category        0
Product             0
Order_Quantity      0
Unit_Cost           0
Unit_Price          0
Profit              0
Cost                0
Revenue             0
dtype: int64


In [ ]:
# Remove rows with missing values using `dropna()`
cleaned_df = df.dropna()  # Drops rows with any NaN values
print(cleaned_df.head())

         Date  Day     Month  Year  Customer_Age       Age_Group  \
0  2013-11-26   26  November  2013            19     Youth (<25)   
1  2015-11-26   26  November  2015            19     Youth (<25)   
2  2014-03-23   23     March  2014            49  Adults (35-64)   
3  2016-03-23   23     March  2016            49  Adults (35-64)   
4  2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike         

In [ ]:
# Fill missing values with a default value (e.g., 0)
filled_df = df.fillna(0)  # Replaces all NaN values with 0
print(filled_df.head())

         Date  Day     Month  Year  Customer_Age       Age_Group  \
0  2013-11-26   26  November  2013            19     Youth (<25)   
1  2015-11-26   26  November  2015            19     Youth (<25)   
2  2014-03-23   23     March  2014            49  Adults (35-64)   
3  2016-03-23   23     March  2016            49  Adults (35-64)   
4  2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike         

In [ ]:
# Forward fill: Fill missing values with the previous value
ffill_df = df.ffill()  # Forward fill
print(ffill_df.head())

         Date  Day     Month  Year  Customer_Age       Age_Group  \
0  2013-11-26   26  November  2013            19     Youth (<25)   
1  2015-11-26   26  November  2015            19     Youth (<25)   
2  2014-03-23   23     March  2014            49  Adults (35-64)   
3  2016-03-23   23     March  2016            49  Adults (35-64)   
4  2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike         

In [ ]:
# Backward fill: Fill missing values with the next value
bfill_df = df.bfill()  # Backward fill
print(bfill_df.head())

         Date  Day     Month  Year  Customer_Age       Age_Group  \
0  2013-11-26   26  November  2013            19     Youth (<25)   
1  2015-11-26   26  November  2015            19     Youth (<25)   
2  2014-03-23   23     March  2014            49  Adults (35-64)   
3  2016-03-23   23     March  2016            49  Adults (35-64)   
4  2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike         

In [ ]:
# Create a boolean mask to identify missing values
boolean_mask = df.isna()
print(boolean_mask.head())  # True where NaN, False otherwise

    Date    Day  Month   Year  Customer_Age  Age_Group  Customer_Gender  \
0  False  False  False  False         False      False            False   
1  False  False  False  False         False      False            False   
2  False  False  False  False         False      False            False   
3  False  False  False  False         False      False            False   
4  False  False  False  False         False      False            False   

   Country  State  Product_Category  Sub_Category  Product  Order_Quantity  \
0    False  False             False         False    False           False   
1    False  False             False         False    False           False   
2    False  False             False         False    False           False   
3    False  False             False         False    False           False   
4    False  False             False         False    False           False   

   Unit_Cost  Unit_Price  Profit   Cost  Revenue  
0      False       False   Fa

In [ ]:
# Remove rows where 'Revenue' has missing values
filtered_df = df[~df['Revenue'].isna()]  # Keeps only rows where 'Revenue' is not NaN
print(filtered_df.head())

         Date  Day     Month  Year  Customer_Age       Age_Group  \
0  2013-11-26   26  November  2013            19     Youth (<25)   
1  2015-11-26   26  November  2015            19     Youth (<25)   
2  2014-03-23   23     March  2014            49  Adults (35-64)   
3  2016-03-23   23     March  2016            49  Adults (35-64)   
4  2014-05-15   15       May  2014            47  Adults (35-64)   

  Customer_Gender    Country             State Product_Category Sub_Category  \
0               M     Canada  British Columbia      Accessories   Bike Racks   
1               M     Canada  British Columbia      Accessories   Bike Racks   
2               M  Australia   New South Wales      Accessories   Bike Racks   
3               M  Australia   New South Wales      Accessories   Bike Racks   
4               F  Australia   New South Wales      Accessories   Bike Racks   

               Product  Order_Quantity  Unit_Cost  Unit_Price  Profit  Cost  \
0  Hitch Rack - 4-Bike         

In [ ]:
# Replace missing 'Revenue' values with the mean revenue
custom_filled_df = df.copy()
mean_revenue = custom_filled_df['Revenue'].mean()
custom_filled_df['Revenue'] = custom_filled_df['Revenue'].fillna(mean_revenue)
print(custom_filled_df[['Date', 'Revenue']].head())

         Date  Revenue
0  2013-11-26      950
1  2015-11-26      950
2  2014-03-23     2401
3  2016-03-23     2088
4  2014-05-15      418


# 6. Grouping, Merging, and Concatenating

### **6.1 Grouping Data**

### **What is Grouping?**  
Grouping is a process used to **split data into categories**, **apply calculations**, and **combine the results**. This strategy is known as the **split-apply-combine** approach:  

1. **Split**: Divide the dataset into groups based on one or more columns (e.g., "brand").
2. **Apply**: Perform an aggregation (e.g., `sum()`, `mean()`, `count()`) on each group.
3. **Combine**: Merge the results back into a single dataset.

---

### **Key Grouping Syntax in Pandas**  

| **Function**     | **Description**                                                | **Example Syntax**                       |
|------------------|----------------------------------------------------------------|-------------------------------------------|
| `groupby()`      | Splits data into groups based on column values                 | `df.groupby('column_name')`               |
| `mean()`         | Calculates the mean (average) for each group                   | `df.groupby('Brand')['Price'].mean()`     |
| `sum()`          | Calculates the sum of values for each group                    | `df.groupby('Category')['Sales'].sum()`   |
| `count()`        | Counts the number of records in each group                     | `df.groupby('Type').count()`              |
| `min()`, `max()` | Finds the minimum or maximum values for each group             | `df.groupby('Region')['Revenue'].max()`   |
| `agg()`          | Applies multiple aggregation functions to the same group       | `df.groupby('Product').agg(['sum', 'mean'])` |

---

### **Split-Apply-Combine Process Illustration**

<div style="text-align: center;">
  <img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/03.08-split-apply-combine.png" alt="Split-Apply-Combine" width="500">
</div>

This image demonstrates how the data is:
- **Split** by keys (`A`, `B`, `C`).
- **Apply**: A sum operation is performed.
- **Combine**: The sums are merged back into a summarized table.

---

In [ ]:
# Group by a single column ('Country') and calculate the average revenue
average_revenue_by_country = df.groupby('Country')['Revenue'].mean()
print(average_revenue_by_country.head())  # Display first 5 rows

Country
Australia         889.959016
Canada            559.721964
France            766.764139
Germany           809.028293
United Kingdom    781.659031
Name: Revenue, dtype: float64


In [ ]:
# Group by multiple columns ('Country' and 'State') and calculate total revenue
total_revenue_by_region = df.groupby(['Country', 'State'])['Revenue'].sum()
print(total_revenue_by_region.head())  # Display first 5 rows

Country    State          
Australia  New South Wales    9203495
           Queensland         5066267
           South Australia    1397274
           Tasmania            580184
           Victoria           5054839
Name: Revenue, dtype: int64


In [ ]:
# Count the number of orders by product category
order_count_by_category = df.groupby('Product_Category')['Order_Quantity'].count()
print(order_count_by_category)  # Display all categories

Product_Category
Accessories    70120
Bikes          25982
Clothing       16934
Name: Order_Quantity, dtype: int64


In [ ]:
# Group by 'Product' and apply multiple aggregation functions on 'Revenue' and 'Profit'
aggregated_data = df.groupby('Product').agg({'Revenue': ['sum', 'mean'], 'Profit': ['sum', 'max']})
print(aggregated_data.head())  # Display first 5 products

                       Revenue              Profit      
                           sum        mean     sum   max
Product                                                 
AWC Logo Cap            549220  126.025700   78008    61
All-Purpose Bike Stand  342664  758.106195  201064  1083
Bike Wash - Dissolver   198745  110.169069  116008   157
Classic Vest, L         268943  845.732704  157319  1181
Classic Vest, M         278764  871.137500  161740  1181


In [ ]:
# Iterate through groups by 'Age Group' and display the first 3 rows in each group
for age_group, group_data in df.groupby('Age_Group'):
    print(f"\nAge Group: {age_group}")
    print(group_data[['Date', 'Revenue', 'Profit']].head(3))


Age Group: Adults (35-64)
         Date  Revenue  Profit
2  2014-03-23     2401    1366
3  2016-03-23     2088    1188
4  2014-05-15      418     238

Age Group: Seniors (64+)
           Date  Revenue  Profit
124  2014-04-27      235     145
125  2016-04-27      118      73
134  2014-02-19      197     107

Age Group: Young Adults (25-34)
          Date  Revenue  Profit
10  2013-07-30      758     398
11  2015-07-30      758     398
12  2013-07-15      664     349

Age Group: Youth (<25)
          Date  Revenue  Profit
0   2013-11-26      950     590
1   2015-11-26      950     590
54  2013-07-17      907     502


In [ ]:
# Custom grouping: Group data based on revenue thresholds
custom_groups = df.groupby(lambda x: "High Revenue" if df.loc[x, 'Revenue'] > 1000 else "Low Revenue")
for group_name, group in custom_groups:
    print(f"\nGroup: {group_name}")
    print(group[['Date', 'Country', 'Revenue']].head(3))


Group: High Revenue
         Date    Country  Revenue
2  2014-03-23  Australia     2401
3  2016-03-23  Australia     2088
8  2014-02-22  Australia     2086

Group: Low Revenue
         Date    Country  Revenue
0  2013-11-26     Canada      950
1  2015-11-26     Canada      950
4  2014-05-15  Australia      418


# 7. Time-Series Data

### **7.1 Creating Time-Series Data**

### **What is Time-Series Data?**  
Time-series data is a sequence of data points recorded at successive points in time, often at regular intervals (e.g., hourly, daily, or yearly).  
Examples of time-series data include:
- **Stock prices** over time.
- **Weather data** (e.g., temperature recorded hourly).
- **Sales data** (e.g., daily or monthly revenue).

In pandas, time-series data is handled using `DatetimeIndex`, which allows for advanced date-based indexing, filtering, and calculations.

---

### **Key Functions for Time-Series Creation:**

| **Function**       | **Description**                                                         | **Example Syntax**                                   |
|--------------------|--------------------------------------------------------------------------|-----------------------------------------------------|
| `to_datetime()`    | Converts a date string or a column to a `datetime` object                | `pd.to_datetime(df['Date'])`                        |
| `date_range()`     | Creates a sequence of dates at regular intervals                         | `pd.date_range(start='2022-01-01', periods=10)`     |
| `set_index()`      | Sets the date/time column as the index for time-based filtering and slicing | `df.set_index('Date', inplace=True)`                |
| `resample()`       | Resamples time-series data to a different frequency                      | `df.resample('M').mean()`                           |

---

### **Time-Series to Cross-Sectional Data Illustration**

<div style="text-align: center;">
  <img src="https://ars.els-cdn.com/content/image/3-s2.0-B9780128147610000125-f12-28-9780128147610.jpg" alt="Time-Series to Cross-Sectional Transformation" width="600">
</div>

---

### **Explanation of the Image:**

This image illustrates the conversion from **time-series data (A)** to **cross-sectional data (B)**:
1. **Time-Series Data (A)**: The left section represents a dataset where each row corresponds to a specific time point (`Date`, `inputYt`).
2. **Windowing Process**: A **window** captures several prior observations (`inputYt-5` to `inputYt`) as features for prediction. The future observation (`inputYt+1`) is used as the target.
3. **Cross-Sectional Data (B)**: The right section shows the tabular form of the data, where each row contains input features (`inputYt-5`, `inputYt-4`, ..., `inputYt`) and the corresponding horizon value (`inputYt+1`).

This transformation is crucial for:
- **Time-series forecasting**: Preparing data for predictive modeling.
- Converting **sequential observations** into a structure suitable for **machine learning models**.

---


In [ ]:
# Convert 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])  # Convert to datetime format
print(df['Date'].head())  # Display the first 5 converted dates

0   2013-11-26
1   2015-11-26
2   2014-03-23
3   2016-03-23
4   2014-05-15
Name: Date, dtype: datetime64[ns]


In [ ]:
# Set the 'Date' column as the index for time-series operations
df.set_index('Date', inplace=True)  # Set 'Date' as the index
print(df.head())  # Display the first 5 rows with 'Date' as index

            Day     Month  Year  Customer_Age       Age_Group Customer_Gender  \
Date                                                                            
2013-11-26   26  November  2013            19     Youth (<25)               M   
2015-11-26   26  November  2015            19     Youth (<25)               M   
2014-03-23   23     March  2014            49  Adults (35-64)               M   
2016-03-23   23     March  2016            49  Adults (35-64)               M   
2014-05-15   15       May  2014            47  Adults (35-64)               F   

              Country             State Product_Category Sub_Category  \
Date                                                                    
2013-11-26     Canada  British Columbia      Accessories   Bike Racks   
2015-11-26     Canada  British Columbia      Accessories   Bike Racks   
2014-03-23  Australia   New South Wales      Accessories   Bike Racks   
2016-03-23  Australia   New South Wales      Accessories   Bike Rac

In [ ]:
#  Create a custom time-series DataFrame using `date_range()`
custom_date_range = pd.date_range(start='2023-01-01', periods=10, freq='D')  # 10 days from Jan 1, 2023
custom_time_series_df = pd.DataFrame({'Sales': np.random.randint(100, 500, size=10)}, index=custom_date_range)
print(custom_time_series_df)  # Display the generated time-series DataFrame

            Sales
2023-01-01    438
2023-01-02    145
2023-01-03    408
2023-01-04    217
2023-01-05    203
2023-01-06    235
2023-01-07    199
2023-01-08    266
2023-01-09    442
2023-01-10    292


In [ ]:
# Slice time-series data by date range
print("Slicing Time-Series Data (January 2 to January 5, 2023):")
print(custom_time_series_df['2023-01-02':'2023-01-05'])  # Show specific date range

Slicing Time-Series Data (January 2 to January 5, 2023):
            Sales
2023-01-02    145
2023-01-03    408
2023-01-04    217
2023-01-05    203


In [ ]:
# Extract year, month, and day from the datetime index
df['Year'] = df.index.year  # Extract year
df['Month'] = df.index.month  # Extract month
df['Day'] = df.index.day  # Extract day
print(df[['Year', 'Month', 'Day']].head())  # Display the extracted columns

            Year  Month  Day
Date                        
2013-11-26  2013     11   26
2015-11-26  2015     11   26
2014-03-23  2014      3   23
2016-03-23  2016      3   23
2014-05-15  2014      5   15


In [ ]:
# Calculate time differences from the earliest date
print("Calculating Time Differences from the Start Date:")
df['Time_from_start'] = df.index - df.index.min()  # Calculate timedelta from the first date
print(df[['Time_from_start']].head())  # Display the time differences

Calculating Time Differences from the Start Date:
           Time_from_start
Date                      
2013-11-26       1060 days
2015-11-26       1790 days
2014-03-23       1177 days
2016-03-23       1908 days
2014-05-15       1230 days


In [ ]:
# Calculate cumulative revenue over time
df['Cumulative_Revenue'] = df['Revenue'].cumsum()  # Calculate cumulative sum of revenue
print(df[['Revenue', 'Cumulative_Revenue']].head())  # Display the cumulative revenue

            Revenue  Cumulative_Revenue
Date                                   
2013-11-26      950                 950
2015-11-26      950                1900
2014-03-23     2401                4301
2016-03-23     2088                6389
2014-05-15      418                6807


### **7.2 Resampling Time-Series Data**

### **What is Resampling?**  
Resampling is the process of **changing the frequency** of time-series data, either by:
- **Down-sampling:** Reducing the frequency (e.g., converting hourly data to daily).
- **Up-sampling:** Increasing the frequency (e.g., converting daily data to hourly).

---

### **Use Cases of Resampling:**  
- **Down-sampling Example:** Calculate the **total monthly sales** using `resample('M').sum()`.
- **Up-sampling Example:** Create hourly data points by filling in missing values using `resample('H').ffi to reduce frequency.

---

### **Key Pandas Methods for Resampling:**

| **Method**      | **Description**                                                 | **Example Syntax**                              |
|-----------------|------------------------------------------------------------------|-------------------------------------------------|
| `resample()`    | Groups time-series data into the specified frequency             | `df.resample('M').mean()`                       |
| `ffill()`       | Forward-fills missing values after up-sampling                   | `df.resample('H').ffill()`                      |
| `bfill()`       | Backward-fills missing values after up-sampling                  | `df.resample('H').bfill()`                      |
| `sum()`         | Calculates the sum of values for the new time window             | `df.resample('W

### **Illustration of Time-Series Frequencies**

<div style="text-align: center;">
  <img src="https://sqlrelease.com//wp-content/uploads/2018/09/Python-use-case-Resampling-time-series-data-Upsampling-and-downsampling-SQL-Server-2017-Upsampling-and-downsampling.png" alt="Time-Seri3s Resampling" width="400">
</div>

---

### **Explanation of the Image:**  
- The image demonstrates **time-series frequencies** ranging from **yearly** to **secondly** data.
- The **upward arrow** represents **up-sampling**, where data points are inserted to increase frequency.
- The **downward arrow** represents **down-sampling**, where multiple data points are aggregated to urly_sales.head(10))



In [ ]:
# Downsample: Calculate total sales per month
monthly_sales = df.resample('ME').sum()  # Resample data by month and calculate the sum
print("\nMonthly Sales Summary:")
print(monthly_sales.head(2))


Monthly Sales Summary:
             Day  Month    Year  Customer_Age  \
Date                                            
2011-01-31  3100    188  378068          6503   
2011-02-28  2415    342  343881          5705   

                                                    Age_Group  \
Date                                                            
2011-01-31  Youth (<25)Young Adults (25-34)Youth (<25)Adul...   
2011-02-28  Adults (35-64)Adults (35-64)Young Adults (25-3...   

                                              Customer_Gender  \
Date                                                            
2011-01-31  MFMMMFFMMMMFFMFMFMFFMFMMMFFMMFFFMMFFFMFMMFMFFM...   
2011-02-28  MFFMMFMMMFMMMFMFFMMMFFMFMMMMMFMMMFMFMFMFFMMFFM...   

                                                      Country  \
Date                                                            
2011-01-31  AustraliaFranceCanadaUnited StatesUnited State...   
2011-02-28  United StatesUnited KingdomAustraliaAustraliaC... 

In [ ]:
# Remove duplicate index by grouping and summing values
df = df.groupby(df.index).sum()

# Perform upsampling and forward-fill missing values
daily_sales_ffill = df.resample('D').ffill()  # Resample to daily frequency and fill missing data
print("\nDaily Sales Summary (Upsampled and Forward-Filled):")
print(daily_sales_ffill.head(2))



Daily Sales Summary (Upsampled and Forward-Filled):
            Day  Month   Year  Customer_Age  \
Date                                          
2011-01-01    5      5  10055           154   
2011-01-02    8      4   8044           148   

                                                    Age_Group Customer_Gender  \
Date                                                                            
2011-01-01  Youth (<25)Young Adults (25-34)Youth (<25)Adul...           MFMMM   
2011-01-02  Adults (35-64)Adults (35-64)Young Adults (25-3...            FFMM   

                                                    Country  \
Date                                                          
2011-01-01  AustraliaFranceCanadaUnited StatesUnited States   
2011-01-02    AustraliaUnited StatesUnited KingdomAustralia   

                                                        State  \
Date                                                            
2011-01-01  VictoriaYvelineBritish ColumbiaCalifor